SET SERVEROUTPUT ON SIZE 1000000;
SET LINESIZE 1000;
set pagesize 1000;
set long 1000;

/*
1. Connect using: -
      sqlplus / as DBA_USERS
2. Use these select statements to identify which accounts are locked and/or expired: -
    SELECT USERNAME,ACCOUNT_STATUS FROM DBA_USERS;
    SELECT USERNAME FROM DBA_USERS;
    SELECT USERNAME FROM DBA_USERS WHERE ACCOUNT_STATUS = 'EXPIRED';
3. Unlock locked accounts: -
    ALTER USER <user_name> ACCOUNT UNLOCK;
4. To unlock change the password of ORACLE_MAINTAINED accounts (i.e. schema accounts)
    4.1. Connect as the SYSTEM account to the SYSTEM schema and list usernames to confirm the account name to change: -
        SELECT * FROM ALL_USERS;
    4.1. Reset the password (put case sensitive passwords in double quotes): -
        alter user WM6 identified by WM6;
*/

-- Put case sensitive passwords in double quotes
ALTER USER <user_name> IDENTIFIED BY <password>;

ALTER USER ORACLE_OCM IDENTIFIED BY "oracle";
ALTER USER OJVMSYS IDENTIFIED BY "oracle";
ALTER USER SYSKM IDENTIFIED BY "oracle";
ALTER USER GSMCATUSER IDENTIFIED BY "oracle";
ALTER USER MDDATA IDENTIFIED BY "oracle";
ALTER USER SYSBACKUP IDENTIFIED BY "oracle";
ALTER USER DIP IDENTIFIED BY "oracle";
ALTER USER SYSDG IDENTIFIED BY "oracle";
ALTER USER APEX_PUBLIC_USER IDENTIFIED BY "oracle";
ALTER USER SPATIAL_CSW_ADMIN_USR IDENTIFIED BY "oracle";
ALTER USER SPATIAL_WFS_ADMIN_USR IDENTIFIED BY "oracle";
ALTER USER GSMUSER IDENTIFIED BY "oracle";
ALTER USER AUDSYS IDENTIFIED BY "oracle";
ALTER USER FLOWS_FILES IDENTIFIED BY "oracle";
ALTER USER DVF IDENTIFIED BY "oracle";
ALTER USER MDSYS IDENTIFIED BY "oracle";
ALTER USER ORDSYS IDENTIFIED BY "oracle";
ALTER USER DBSNMP IDENTIFIED BY "oracle";
ALTER USER WMSYS IDENTIFIED BY "oracle";
ALTER USER APEX_040200 IDENTIFIED BY "oracle";
ALTER USER APPQOSSYS IDENTIFIED BY "oracle";
ALTER USER GSMADMIN_INTERNAL IDENTIFIED BY "oracle";
ALTER USER ORDDATA IDENTIFIED BY "oracle";
ALTER USER CTXSYS IDENTIFIED BY "oracle";
ALTER USER ANONYMOUS IDENTIFIED BY "oracle";
ALTER USER XDB IDENTIFIED BY "oracle";
ALTER USER ORDPLUGINS IDENTIFIED BY "oracle";
ALTER USER DVSYS IDENTIFIED BY "oracle";
ALTER USER SI_INFORMTN_SCHEMA IDENTIFIED BY "oracle";
ALTER USER OLAPSYS IDENTIFIED BY "oracle";
ALTER USER LBACSYS IDENTIFIED BY "oracle";
ALTER USER OUTLN IDENTIFIED BY "oracle";


ALTER USER <user_name> ACCOUNT UNLOCK;

ALTER USER ORACLE_OCM ACCOUNT UNLOCK;
ALTER USER OJVMSYS ACCOUNT UNLOCK;
ALTER USER SYSKM ACCOUNT UNLOCK;
ALTER USER XS$NULL ACCOUNT UNLOCK;
ALTER USER GSMCATUSER ACCOUNT UNLOCK;
ALTER USER MDDATA ACCOUNT UNLOCK;
ALTER USER SYSBACKUP ACCOUNT UNLOCK;
ALTER USER DIP ACCOUNT UNLOCK;
ALTER USER SYSDG ACCOUNT UNLOCK;
ALTER USER APEX_PUBLIC_USER ACCOUNT UNLOCK;
ALTER USER SPATIAL_CSW_ADMIN_USR ACCOUNT UNLOCK;
ALTER USER SPATIAL_WFS_ADMIN_USR ACCOUNT UNLOCK;
ALTER USER GSMUSER ACCOUNT UNLOCK;
ALTER USER AUDSYS ACCOUNT UNLOCK;
ALTER USER FLOWS_FILES ACCOUNT UNLOCK;
ALTER USER DVF ACCOUNT UNLOCK;
ALTER USER MDSYS ACCOUNT UNLOCK;
ALTER USER ORDSYS ACCOUNT UNLOCK;
ALTER USER DBSNMP ACCOUNT UNLOCK;
ALTER USER WMSYS ACCOUNT UNLOCK;
ALTER USER APEX_040200 ACCOUNT UNLOCK;
ALTER USER APPQOSSYS ACCOUNT UNLOCK;
ALTER USER GSMADMIN_INTERNAL ACCOUNT UNLOCK;
ALTER USER ORDDATA ACCOUNT UNLOCK;
ALTER USER CTXSYS ACCOUNT UNLOCK;
ALTER USER ANONYMOUS ACCOUNT UNLOCK;
ALTER USER XDB ACCOUNT UNLOCK;
ALTER USER ORDPLUGINS ACCOUNT UNLOCK;
ALTER USER DVSYS ACCOUNT UNLOCK;
ALTER USER SI_INFORMTN_SCHEMA ACCOUNT UNLOCK;
ALTER USER OLAPSYS ACCOUNT UNLOCK;
ALTER USER LBACSYS ACCOUNT UNLOCK;
ALTER USER OUTLN ACCOUNT UNLOCK;
ALTER USER SYSTEM ACCOUNT UNLOCK;
ALTER USER SYS ACCOUNT UNLOCK;