REM @ECHO OFF

PUSHD ..\..

SET TRUECRYPT_FOLDER_NAME=%CD%\encryption\truecrypt\windows
SET TRUECRYPT_PROGRAM_NAME=%TRUECRYPT_FOLDER_NAME%\TrueCrypt.exe
SET CONTAINER_FILENAME=%CD%\file

ECHO Using TrueCrypt Executable "%TRUECRYPT_PROGRAM_NAME%"...

ECHO Dismounting "%CONTAINER_FILENAME%"...

START /WAIT "Dismounting..." "%TRUECRYPT_PROGRAM_NAME%" "%CONTAINER_FILENAME%" /d /s /q 2>&1