@ECHO OFF

SET INTERACTIVE=1
echo %cmdcmdline% | find /i "%ComSpec%" >nul
IF NOT errorlevel 1 SET INTERACTIVE=0

::Create a sortable date.
FOR /F "tokens=1-4 delims=/ " %%I IN ('ECHO %DATE%') DO SET CURRENT_DATE=%%K-%%J-%%I
::Create a sortable time.
FOR /F "tokens=1-3 delims=: " %%I IN ('ECHO %TIME%') DO SET CURRENT_TIME=%%I-%%J-%%K
::Replace the "." with a "-"
FOR /F "tokens=1-2 delims=. " %%I IN ('ECHO %CURRENT_TIME%') DO SET CURRENT_TIME=%%I-%%J

SET SCRIPT_DRIVE=%~d0
SET SCRIPT_FOLDER=%~dp0
::Remove a trailing slash, if one is present.
IF %SCRIPT_FOLDER:~-1%==\ SET SCRIPT_FOLDER=%SCRIPT_FOLDER:~0,-1%

::Display help only.
SET HELP_ONLY=0
IF "%~1"=="/?" SET HELP_ONLY=1
IF "%~1"=="-?" SET HELP_ONLY=1
IF "%~1"=="-h" SET HELP_ONLY=1
IF "%~1"=="/help" SET HELP_ONLY=1
IF "%~1"=="--help" SET HELP_ONLY=1

IF NOT "%~1"=="" (
	IF "%HELP_ONLY%"=="0" (
		SET SOURCE_TO_BACKUP=%~1
	) ELSE (
		SET SOURCE_TO_BACKUP=%SCRIPT_FOLDER%\..\
	)
) else (
	SET SOURCE_TO_BACKUP=%SCRIPT_FOLDER%\..\
)
CALL %SCRIPT_FOLDER%\is-directory.cmd "!SOURCE_TO_BACKUP!"
SET RETURN_CODE=%errorlevel%
if %RETURN_CODE%==1 (
	:: Convert the relative path to an absolute path.
	PUSHD "!SOURCE_TO_BACKUP!"
	SET SOURCE_TO_BACKUP=!CD!
	POPD
)
::Remove a trailing slash, if one is present.
IF !SOURCE_TO_BACKUP:~-1!==\ SET SOURCE_TO_BACKUP=!SOURCE_TO_BACKUP:~0,-1!

IF NOT "%~2"=="" (
	SET BACKUP_FOLDER=%~2
) else (
	SET BACKUP_FOLDER_NAME=backup
	SET BACKUP_FOLDER=%SCRIPT_DRIVE%\!BACKUP_FOLDER_NAME!
)
CALL %SCRIPT_FOLDER%\is-directory.cmd "!BACKUP_FOLDER!"
SET RETURN_CODE=%errorlevel%
if %RETURN_CODE%==1 (
	:: Convert the relative path to an absolute path.
	PUSHD "!BACKUP_FOLDER!"
	SET BACKUP_FOLDER=!CD!
	POPD
)
::Remove a trailing slash, if one is present.
IF !BACKUP_FOLDER:~-1!==\ SET BACKUP_FOLDER=!BACKUP_FOLDER:~0,-1!

SET BACKUP_PROGRAM="C:\apps\utility\archive\7-ZipPortable\App\7-Zip64\7z.exe" a -ttar
SET SORTABLE_DATE_TIME=%CURRENT_DATE%-%CURRENT_TIME%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET SOURCE_TO_BACKUP_WITHOUT_PATH=%SOURCE_TO_BACKUP_WITHOUT_PATH:*\=%
SET ARCHIVE_FILE=%BACKUP_FOLDER%\%SOURCE_TO_BACKUP_WITHOUT_PATH%[%SORTABLE_DATE_TIME%].tar

::Display help only.
IF "%HELP_ONLY%"=="1%" GOTO END

ECHO INTERACTIVE:%INTERACTIVE%.
ECHO HELP_ONLY:%HELP_ONLY%.
ECHO SCRIPT_DRIVE:%SCRIPT_DRIVE%.
ECHO SCRIPT_FOLDER:%SCRIPT_FOLDER%.
ECHO SOURCE_TO_BACKUP:!SOURCE_TO_BACKUP!.
ECHO SOURCE_TO_BACKUP_WITHOUT_PATH:%SOURCE_TO_BACKUP_WITHOUT_PATH%.
ECHO BACKUP_FOLDER:%BACKUP_FOLDER%.
ECHO BACKUP_PROGRAM:%BACKUP_PROGRAM%.
ECHO CURRENT_DATE:%CURRENT_DATE%.
ECHO CURRENT_TIME:%CURRENT_TIME%.
ECHO SORTABLE_DATE_TIME=%SORTABLE_DATE_TIME%.
ECHO ARCHIVE_FILE=%ARCHIVE_FILE%.

:END